export interface IOP {
    OP_FALSE: number,
    OP_0: number,
    OP_PUSHDATA1: number,
    OP_PUSHDATA2: number,
    OP_PUSHDATA4: number,
    OP_1NEGATE: number,
    OP_RESERVED: number,
    OP_TRUE: number,
    OP_1: number,
    OP_2: number,
    OP_3: number,
    OP_4: number,
    OP_5: number,
    OP_6: number,
    OP_7: number,
    OP_8: number,
    OP_9: number,
    OP_10: number,
    OP_11: number,
    OP_12: number,
    OP_13: number,
    OP_14: number,
    OP_15: number,
    OP_16: number,

    // control
    OP_NOP: number,
    OP_VER: number,
    OP_IF: number,
    OP_NOTIF: number,
    OP_VERIF: number,
    OP_VERNOTIF: number,
    OP_ELSE: number,
    OP_ENDIF: number,
    OP_VERIFY: number,
    OP_RETURN: number,

    // stack ops
    OP_TOALTSTACK: number,
    OP_FROMALTSTACK: number,
    OP_2DROP: number,
    OP_2DUP: number,
    OP_3DUP: number,
    OP_2OVER: number,
    OP_2ROT: number,
    OP_2SWAP: number,
    OP_IFDUP: number,
    OP_DEPTH: number,
    OP_DROP: number,
    OP_DUP: number,
    OP_NIP: number,
    OP_OVER: number,
    OP_PICK: number,
    OP_ROLL: number,
    OP_ROT: number,
    OP_SWAP: number,
    OP_TUCK: number,

    // data manipulation ops
    OP_CAT: number,
    OP_SUBSTR: number, // Replaced in BSV
    OP_SPLIT: number,
    OP_LEFT: number, // Replaced in BSV
    OP_NUM2BIN: number,
    OP_RIGHT: number, // Replaced in BSV
    OP_BIN2NUM: number,
    OP_SIZE: number,

    // bit logic
    OP_INVERT: number,
    OP_AND: number,
    OP_OR: number,
    OP_XOR: number,
    OP_EQUAL: number,
    OP_EQUALVERIFY: number,
    OP_RESERVED1: number,
    OP_RESERVED2: number,

    // numeric
    OP_1ADD: number,
    OP_1SUB: number,
    OP_2MUL: number,
    OP_2DIV: number,
    OP_NEGATE: number,
    OP_ABS: number,
    OP_NOT: number,
    OP_0NOTEQUAL: number,

    OP_ADD: number,
    OP_SUB: number,
    OP_MUL: number,
    OP_DIV: number,
    OP_MOD: number,
    OP_LSHIFT: number,
    OP_RSHIFT: number,

    OP_BOOLAND: number,
    OP_BOOLOR: number,
    OP_NUMEQUAL: number,
    OP_NUMEQUALVERIFY: number,
    OP_NUMNOTEQUAL: number,
    OP_LESSTHAN: number,
    OP_GREATERTHAN: number,
    OP_LESSTHANOREQUAL: number,
    OP_GREATERTHANOREQUAL: number,
    OP_MIN: number,
    OP_MAX: number,

    OP_WITHIN: number,

    // crypto
    OP_RIPEMD160: number,
    OP_SHA1: number,
    OP_SHA256: number,
    OP_HASH160: number,
    OP_HASH256: number,
    OP_CODESEPARATOR: number,
    OP_CHECKSIG: number,
    OP_CHECKSIGVERIFY: number,
    OP_CHECKMULTISIG: number,
    OP_CHECKMULTISIGVERIFY: number,

    // expansion
    OP_NOP1: number,
    OP_NOP2: number,
    OP_NOP3: number,
    OP_NOP4: number,
    OP_NOP5: number,
    OP_NOP6: number,
    OP_NOP7: number,
    OP_NOP8: number,
    OP_NOP9: number,
    OP_NOP10: number,
    OP_NOP11: number,
    OP_NOP12: number,
    OP_NOP13: number,
    OP_NOP14: number,
    OP_NOP15: number,
    OP_NOP16: number,
    OP_NOP17: number,
    OP_NOP18: number,
    OP_NOP19: number,
    OP_NOP20: number,
    OP_NOP21: number,
    OP_NOP22: number,
    OP_NOP23: number,
    OP_NOP24: number,
    OP_NOP25: number,
    OP_NOP26: number,
    OP_NOP27: number,
    OP_NOP28: number,
    OP_NOP29: number,
    OP_NOP30: number,
    OP_NOP31: number,
    OP_NOP32: number,
    OP_NOP33: number,
    OP_NOP34: number,
    OP_NOP35: number,
    OP_NOP36: number,
    OP_NOP37: number,
    OP_NOP38: number,
    OP_NOP39: number,
    OP_NOP40: number,
    OP_NOP41: number,
    OP_NOP42: number,
    OP_NOP43: number,
    OP_NOP44: number,
    OP_NOP45: number,
    OP_NOP46: number,
    OP_NOP47: number,
    OP_NOP48: number,
    OP_NOP49: number,
    OP_NOP50: number,
    OP_NOP51: number,
    OP_NOP52: number,
    OP_NOP53: number,
    OP_NOP54: number,
    OP_NOP55: number,
    OP_NOP56: number,
    OP_NOP57: number,
    OP_NOP58: number,
    OP_NOP59: number,
    OP_NOP60: number,
    OP_NOP61: number,
    OP_NOP62: number,
    OP_NOP63: number,
    OP_NOP64: number,
    OP_NOP65: number,
    OP_NOP66: number,
    OP_NOP67: number,
    OP_NOP68: number,
    OP_NOP69: number,
    OP_NOP70: number,
    OP_NOP71: number,
    OP_NOP72: number,
    OP_NOP73: number,
    OP_NOP77: number,

    // template matching params
    OP_SMALLDATA: number,
    OP_SMALLINTEGER: number,
    OP_PUBKEYS: number,
    OP_PUBKEYHASH: number,
    OP_PUBKEY: number,

    OP_INVALIDOPCODE: number,
}